version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=my-apps-user-name
      - POSTGRESQL_PASSWORD=my-apps-pass
      - POSTGRESQL_DATABASE=my-apps-db