name: On Push Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install packages
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service ${{ secrets.SERVICE }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}